#_config.yml
tile: Dienay Lima
description: Blog e portfólio de Desenvolvedor Web Full-Stack
url: "https://dienay.github.io/portfolio"
lang: pt-BR

# Configurações do blog
permalink: /artigos/:year/:slug
paginate: 5
paginate_path: "/artigos/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
